# Generated by Django 5.2.4 on 2025-07-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pilotlog", "0002_alter_aircraft_id_alter_aircraftmeta_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="airport",
            name="source_guid",
            field=models.CharField(
                blank=True, help_text="Original GUID from import source", max_length=36
            ),
        ),
    ]
